web/urls.py
from django.urls import path
from django.urls.conf import include

from web.views import index, product, subscribe, contact

app_name = "web"


urlpatterns = [
    path('',index,name="index"),
    path('subscribe',subscribe,name="subscribe"),
    path('contact',contact,name="contact"),
    path('product/<int:pk>',product,name="product")

]

wibbits/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("web.urls",namespace="web"))
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

web/models.py
from os import name
from django.db import models
from django.db.models.base import Model


CONTENT_TYPE = (
    ("blog_post", "Blog Post"),
    ("webinar", "Webinar"),
    ("report", "Report")
) 

COMPANY_SIZE = (
    ("1", "1-10"),
    ("2", "11-50"),
    ("3", "51-200"),
    ("4", "201-500"),
)

INDUSTRY = (
    ("agriculture", "Agriculture"),
    ("banking_&_finance", "Banking & Finance"),
    ("business_services_&_software", "Business Services & Software"),
)

JOB_ROLE = (
    ("c_suite", "C-Suite"),
    ("vp", "VP")
)

COUNTRY = (
    ("united_states", "United States"),
    ("afghanistan", "Afghanistan"),
    ("albania", "Albania"),
    ("algeria", "Algeria"),
    ("american_samoa", "American Samoa")
)


class Subscribe(models.Model):
    email = models.EmailField(max_length=25)

    def __str__(self):
        return self.email


class Customers(models.Model):
    product = models.ForeignKey("web.Product", on_delete=models.CASCADE)
    image = models.FileField(upload_to="customers")
    white_image = models.FileField(upload_to="customers",blank=True,null=True)

    def __str__(self):
        return str(self.id)



class Feature(models.Model):
    image = models.ImageField(upload_to="features")
    icon = models.FileField(upload_to="features")
    icon_background = models.CharField(max_length=25)
    title = models.CharField(max_length=255)
    description = models.TextField(max_length=255)
    testimonial_description = models.TextField(max_length=255)
    testimonial_author = models.CharField(max_length=255)
    author_designation = models.CharField(max_length=255)
    testimonial_logo = models.FileField(upload_to="features")

    def __str__(self):
        return self.testimonial_author


class Review(models.Model):
    title = models.CharField(max_length=155)
    image = models.FileField(upload_to="reviews")
    play = models.FileField(upload_to="reviews")
    logo = models.FileField(upload_to="reviews/logo")

    def __str__(self):
        return str(self.id)


class Testimonial(models.Model):
    image = models.ImageField(upload_to="testimonials")
    logo = models.FileField(upload_to="testimonials\logo",blank=True,null=True)
    description = models.TextField(max_length=255)
    name = models.CharField(max_length=125)
    role = models.CharField(max_length=125)
    company_name = models.CharField(max_length=125)
    is_featured = models.BooleanField()

    def __str__(self):
        return str(self.name)

    class Meta:
        ordering = ["id"]


class Marketing(models.Model):
    image = models.FileField(upload_to="marketing")
    title = models.CharField(max_length=155)
    description = models.TextField(max_length=255)

    def __str__(self):
        return str(self.title)

    class Meta:
        ordering = ["id"]
    


class Product(models.Model):
    image = models.FileField(upload_to="product")
    hero_image = models.FileField(upload_to="product/hero")
    title = models.CharField(max_length=155)
    name = models.CharField(max_length=155)
    logo = models.FileField(upload_to="product/logo")
    description = models.TextField(max_length=255)
    bg_color = models.CharField(max_length=10, default="#fff")
    button_bg_color = models.CharField(max_length=10, default="#fff")

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["id"]



class Blog(models.Model):
    image = models.FileField(upload_to="blog")
    title = models.CharField(max_length=155)
    content_type = models.TextField(max_length=125, choices=CONTENT_TYPE)
    next = models.CharField(max_length=125, default="Read blog")

    def __str__(self):
        return self.title
    
    class Meta :
        ordering = ["id"]


class Contact(models.Model):
    email = models.EmailField()
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    company = models.CharField(max_length=128)
    company_size = models.CharField(max_length=128,choices=COMPANY_SIZE)
    industry = models.CharField(max_length=128,choices=INDUSTRY)
    jobe_role = models.CharField(max_length=128,choices=JOB_ROLE)
    country = models.CharField(max_length=128,choices=COUNTRY)
    user_agreement = models.BooleanField(default=False)

    class Meta:
        ordering = ["id"]

    def __str__(self):
        return self.first_name

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8" />
        <title>Wibbitz: Online video creation made easy</title>
        <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" />
        <link rel="stylesheet" href="{% static 'css/fontello.css' %}" type="text/css" />
        <link
            rel="icon"
            type="image/png"
            sizes="32x32"
            href="{% static 'images/favicon.png' %}"
        />

        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta property="og:image" content="" />
        <meta name="description" content="" />
        <meta name="keywords" content="" />
    </head>
    <body>
        <header>
            <h1 class="left">
                <a href="{% static '#' %}"><img src="{% static 'images/logo.svg' %}" alt="Logo" /></a>
            </h1>
            <nav class="middle">
                <ul>
                    <li><a href="{% static '#' %}">Solutions</a></li>
                    <li><a href="{% static '#' %}">Enterprise</a></li>
                    <li><a href="{% static '#' %}">Use Cases</a></li>
                    <li><a href="{% static '#' %}">Pricing</a></li>
                    <li><a href="{% static '#' %}">Resources</a></li>
                    <li><a href="{% static '#' %}">Company</a></li>
                </ul>
            </nav>
            <nav class="right">
                <ul>
                    
                    <li><a href="{% static '#' %}">Login</a></li>
                    <li><a href="{% static '#' %}" class="button">Get a Demo</a></li>
                </ul>
            </nav>
        </header>
        

        {% block content %}

        {% endblock %}

        <footer>
            <section class="wrapper">
                <section class="top">
                    <div class="item large">
                        <h2>The online video editor trusted by teams to make professional video in minutes.</h2>
                        <div class="social">
                            <ul>
                                <li>
                                    <a href="{% static '#' %}"><img src="{% static 'images/facebook-blue.svg' %}" alt="" /></a>
                                </li>
                                <li>
                                    <a href="{% static '#' %}"><img src="{% static 'images/twitter-blue.svg' %}" alt="" /></a></li>
                                <li>
                                    <a href="{% static '#' %}"><img src="{% static 'images/linkedin-blue.svg' %}" alt="" /></a>
                                </li>
                                <li>
                                    <a href="{% static '#' %}"><img src="{% static 'images/youtube-blue.svg' %}" alt="" /></a>
                                </li>
                                <li>
                                    <a href="{% static '#' %}"><img src="{% static 'images/instagram.svg' %}" alt="" /></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="item">
                        <h5>Solutions</h5>
                        <ul>
                            {% for product in products %}
                            <li>
                                <a href="{% static '#' %}"><img src="{{product.logo.url}}" alt="" /><span>{{product.name}}</span></a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="item">
                        <h5>Use Cases</h5>
                        <ul>
                            <li><a href="{% static '#' %}">Marketing</a></li>
                            <li><a href="{% static '#' %}">Social Media</a></li>
                            <li><a href="{% static '#' %}">Publishers</a></li>
                            <li><a href="{% static '#' %}">Agencies</a></li>
                            <li><a href="{% static '#' %}">Corporate Communications</a></li>
                            <li><a href="{% static '#' %}">Enterprise</a></li>
                        </ul>
                    </div>
                    <div class="item">
                        <h5>Resources</h5>
                        <ul>
                            <li><a href="{% static '#' %}">Learning Center</a></li>
                            <li><a href="{% static '#' %}">Customers</a></li>
                            <li><a href="{% static '#' %}">Video Showcase</a></li>
                        </ul>
                        <a href="{% static '#' %}" class="bold">Pricing</a>
                    </div>
                    <div class="item">
                        <h5>Company</h5>
                        <ul>
                            <li><a href="{% static '#' %}">About Us</a></li>
                            <li><a href="{% static '#' %}">Jobs</a></li>
                            <li><a href="{% static '#' %}">Press</a></li>
                        </ul>
                        <h5>Legal</h5>
                        <ul>
                            <li><a href="{% static '#' %}">Terms and Conditions</a></li>
                            <li><a href="{% static '#' %}">Privacy Policy</a></li>
                        </ul>
                    </div>
                </section>
                <section class="bottom">
                    <div class="title">
                        <img src="{% static 'images/globe-gray.svg' %}" alt="" />
                        <span>Choose language</span>
                    </div>
                    <div class="bottom">
                        <ul>
                            <li><a href="{% static '#' %}">English</a></li>
                            <li><a href="{% static '#' %}">Français</a></li>
                        </ul>
                    </div>
                </section>
            </section>
        </footer>

        <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
        <script src="{% static 'js/sweetalert2.min.js' %}"></script>
        <script src="{% static 'js/script.js' %}"></script>
    </body>
</html>

templates/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <section id="spotlight">
        <section class="wrapper flex-wrapper">
            <section class="content">
                <h1>The quickest and easiest online video editor for every team</h1>
                <p>Wibbitz gives you the freedom to create short form video online in minutes – no experience necessary.</p>
                <form action="{% url 'web:subscribe' %}" method="post" class="ajax">
                    {% csrf_token %}
                    <input type="email" placeholder="Enter your work email" name="email"/>
                    <button type="submit">Get a Demo</button>
                </form>
            </section>
            <div class="right_container">
                <div class="img_container">
                    <img src="{% static 'images/home-hero.svg' %}" alt="" /> 
                </div>
                <a href="{% static '#' %}" class="play-button">
                    <img src="{% static 'images/play.svg' %}" alt="" />
                </a>
            </div>
        </section>
    </section>
    <section id="brands">
        <section class="wrapper">
            <p>Trusted by content creators across the world</p>
            <ul>
                {% for customer in customers %}
                <li><a href="{% static '#' %}"><img src="{{customer.image.url}}" alt="" /></a></li>
                {% endfor %}
            </ul>
        </section>
    </section>
    <section id="fearures">
        {% for feature in features %}
        <section class="feature">
            <section class="wrapper flex-wrapper">
                <div class="img_container">
                    <img src="{{feature.image.url}}" alt="" />
                </div>
                <div class="content">
                    <div class="icon" style="background: {{feature.icon_background}};"><img src="{{feature.icon.url}}" alt="" /></div>
                    <h3>{{feature.title}}</h3>
                    <p>{{feature.description}}</p>
                    <a href="{% static '#' %}" class="button">Get a Demo</a>
                    <div class="review">
                        <hr class="dash" />
                        <blockquote>"{{feature.testimonial_description}}"</blockquote>
                        <span><small>{{feature.testimonial_author}},</small> {{feature.author_designation}}</span>
                        <img src="{{feature.testimonial_logo.url}}" alt="" />
                    </div>
                </div>
            </section>
        </section>
        {% endfor %}
    </section>
    <section id="reviews">
        <section class="wrapper">
            <section class="top">
                <h3>Create video like these leading brands</h3>
            </section>
            <section class="bottom">
                <ul>
                    {% for review in reviews %}
                    <li>
                        <div class="top" style="background-image: url({{review.image.url}});">
                            <span class="play">
                                <img src="{{review.play.url}}" alt="" />
                            </span>
                            <div class="logo">
                                <img src="{{review.logo.url}}" alt="" />
                            </div>
                        </div>
                        <h4>{{review.title}}</h4>
                    </li>
                    {% endfor %}
                </ul>
            </section>
        </section>
    </section>
    <section id="testimonials">
        <section class="wrapper">
            <ul>
                {% for true_testimonial in true_testimonials %}
                <li>
                    <div class="top">
                        <img src="{{true_testimonial.image.url}}" alt="Image" class="cover" />
                        <div class="logo">
                            <img src="{{true_testimonial.logo.url}}" alt="Logo" />
                        </div>
                    </div>
                    <div class="bottom">
                        <blockquote>
                            {{true_testimonial.description}}
                        </blockquote>
                        <h6>{{true_testimonial.name}}</h6>
                        <span>{{true_testimonial.role}}</span>
                        <small>{{true_testimonial.company_name}}</small>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </section>
    </section>
    <section id="features">
        <section class="wrapper">
            <section class="top">
                <h3>
                    Wibbitz gives every team the freedom to create
                </h3>
            </section>
            <section class="content">
                <ul>
                    {% for marketing in marketings %}
                    <li>
                        <div class="content">
                            <a href="{% static '#' %}" class="img_container"><img src="{{marketing.image.url}}" alt="" /></a>
                            <h3><a href="{% static '#' %}">{{marketing.title}}</a></h3>
                            <p>{{marketing.description}}</p>
                            <a href="{% static '#' %}" class="button">Learn More</a>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </section>
            <section class="bottom">
                <span class="icon"><img src="{% static 'images/star.svg' %}" alt="" /></span>
                <div class="element">
                    <p>Empower your whole team to create an engaging video in 7 minutes or less.</p>
                    <a href="{% static '#' %}" class="button">Get a Demo</a>
                </div>
            </section>
        </section>
    </section>
    <section id="products">
        <section class="wrapper">
            <section class="top">
                <h3>Our three video solutions are built for every type of business</h3>
            </section>
            <ul>
                {% for product in products %}
                <li class="one" style="background: {{product.bg_color}};">
                    <div class="logo">
                        <img src="{{product.logo.url}}" alt="" />
                    </div>
                    <h1>{{product.name}}</h1>
                    <p>{{product.description}}</p>
                    <a href="{% url 'web:product' pk=product.pk %}" class="button" style="background: {{product.button_bg_color}};">Learn More</a>
                    <div class="img_bottom">
                        <img src="{{product.image.url}}" alt="" class="hero" />
                    </div>
                </li>
                {% endfor %}
            </ul>
        </section>
    </section>
    <section id="blog">
        <section class="wrapper">
            <section class="top">
                <h3>Video resources: Insider advice on how to bring your content to life</h3>
            </section>
            <ul>
                {% for blog in blogs %}
                <li>
                    <img src="{{blog.image.url}}" alt="" />
                    <span style="color:#0055fb" class="label">{{blog.get_content_type_display}}</span>
                    <h2>{{blog.title}}</h2>
                    <a href="{% static '#' %}" class="button">{{blog.next}}</a>
                </li>
                {% endfor %}
            </ul>
            <div class="bottom">
                <a href="{% static '#' %}" class="button">Explore All Resources</a>
            </div>
        </section>
    </section>
    <section id="contact">
        <section class="wrapper">
            <div class="left">
                <h3>Ready to get started?</h3>
                <p>Schedule a demo of our online video editor to start making your own short form videos today. We’ll help you elevate your video content strategy.</p>

                <hr class="line" />

                <div class="testimonials">
                    <h5>Why do content creators choose Wibbitz?</h5>
                    <div class="content">
                        <blockquote>"Wibbitz strengthens the communications strategy at our company by allowing us to produce more videos, faster, while maintaining top level of quality."</blockquote>
                        <h6>Jeff Cucinell</h6>
                        <span class="role">Director of Social Strategy, iHeartRadio</span>
                    </div>
                    <ul class="people">
                        {% for false_testimonial in false_testimonials %}
                        <li >
                            <img src="{{false_testimonial.image.url}}" alt="" /> 
                        </li>
                        {% endfor %}
                    </ul> 
                </div>
                <hr class="line bottom" />
                <div class="companies">
                    <ul>
                        {% for customer in latest_customers %}
                        <li><img src="{{customer.white_image.url}}" alt="" /></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="right">
                <div class="content">
                    <h4>Help us get to know you.</h4>
                    <form action="{% url 'web:contact' %}" method="post" class="ajax">
                        {% csrf_token %}
                        <div class="one_by_two">{{form.email}}</div>
                        <div class="one_by_two">{{form.first_name}}</div>
                        <div class="one_by_two">{{form.last_name}}</div>
                        <div class="one_by_two">{{form.company}}</div>
                        <div class="one_by_two">
                            {{form.company_size}}
                        </div>
                        <div class="one_by_two">
                            {{form.industry}}
                        </div>
                        <div class="one_by_two">
                            {{form.jobe_role}}
                        </div>
                        <div class="one_by_two">
                            {{form.country}}
                        </div>
                        <div class="full checkbox">
                            {{form.user_agreement}}
                            <label for="{{form.user_agreement.id_for_label}}">Yes, I'd like to receive occasional marketing emails from Wibbitz. I have the right to opt out at any time. <a href="{% static '#' %}">View privacy policy.</a></label>
                        </div>
                        <div class="full">
                            <input class="submit" type="submit" value="Get a Demo" />
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </section>
{% endblock %}

templates/product.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <section id="product" style="background: {{product.bg_color}};">
        <section class="wrapper">
            <a href="#" class="logo-badge">
                <img src="{{product.logo.url}}" alt="" />
                {{product.name}}
            </a>
            <h1>{{product.title}}</h1>
            <p>{{product.description}}</p>
            <a href="#" class="button">Get in Touch</a>
            <img src="{{product.hero_image.url}}" alt="Hero Image" class="hero" />
        </section>
    </section>
    <section id="inner-page-brands">
        <section class="wrapper">
            <h6>Leading brands trust Wibbitz for video</h6>
            <ul>
                {% for customer in customers %}
                <li><a href="#"><img src="{{customer.image.url}}" alt="logo-birchbox" /></a></li>
                {% endfor %}
            </ul>
        </section>
    </section>
{% endblock %}